name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        nvim_version:
          - v0.10.2
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit-openresty"
      - uses: leafo/gh-actions-luarocks@v4
      - name: Install test dependencies in Luarocks
        run: |
          luarocks --lua-version=5.1 install fennel
          luarocks --lua-version=5.1 install vusted
      # TODO: Comment out when parinfer tests can be passed on GitHub Actions.
      # - name: Install cargo for parinfer-rust dependenct test
      #   uses: moonrepo/setup-rust@v1
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: ${{ matrix.nvim_version }}
      - name: Run tests
        env:
          # FIXME: Remove `--filter-out` when successfully build `libparinfer_rust.so` in GitHub Actions.
          VUSTED_EXTRA_FLAGS: "--defer-print --suppress-pending --filter-out=parinfer --filter-out=:Fnl"
          VUSTED_EXTRA_ARGS: ""
        run: |
          make -j test
