name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        nvim_version:
          - v0.10.2
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v17
      # TODO: Revert to gh-actions-lua when the actions are up-to-date since
      # nix-installer-actions does not run on `act` as is a known issue.
      # - uses: leafo/gh-actions-lua@v11
      #   with:
      #     luaVersion: "luajit-openresty"
      # - name: Install test dependencies in Luarocks
      #   run: |
      #     luarocks --lua-version=5.1 install fennel
      #     luarocks --lua-version=5.1 install vusted
      # - name: Install cargo for parinfer-rust dependent test
      #   uses: moonrepo/setup-rust@v1
      # - uses: leafo/gh-actions-lua@v10
      #   with:
      #     luaVersion: "luajit-openresty"
      # - uses: leafo/gh-actions-luarocks@v5
      # - name: Install test dependencies in Luarocks
      #   run: |
      #     luarocks --lua-version=5.1 install fennel
      #     luarocks --lua-version=5.1 install vusted
      # - name: Install cargo for parinfer-rust dependent test
      #   uses: moonrepo/setup-rust@v1
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: ${{ matrix.nvim_version }}
      - name: Run tests
        env:
          VUSTED_EXTRA_FLAGS: "--defer-print --suppress-pending"
          VUSTED_EXTRA_ARGS: ""
        run: |
          nix develop --command make -j test
